### ISSUE TITLE
Depend on a separate ruby-libglfw3 gem (like libv8)

### ISSUE THREAD

**Issue by lloeki** [nilium/ruby-glfw3#10]
Instead of depending on this gem's end-user installing glfw3 himself, having a separate gem for glfw3 itself is a nice approach. See how e.g. therubyracer has libv8 as a gem. This makes it incredibly easy to have things "just work", have many versions installed in parallel, handle glfw API changes by making this gem depend on the matching version, manage libglfw3 version with the Gemfile, even optionally provide prebuilt binaries per OS (possibly going as far as removing the need for a C compiler to be installed)...

Of note is that gogl/glfw also does that (although they bundle it straight into the gogl/glfw package). It really makes things easier. Splitting the lib gem from this one (like rubygems/libv8) is better overall though.

I can help in getting things going if you want a hand.

**Comment by nilium** [comment]
This won't be happening because it means I'd have to maintain an additional separate and conflicting version of glfw in addition to what is available from the user and/or their system's dependency manager. Web developers are generally insane and have unusually poor practices (i.e., people trying to use Javascript for anything), so I'd rather not follow their lead on how to organize things.
