### ISSUE TITLE
Won't build on platforms where SIZEOF_INT == SIZEOF_LONG

### ISSUE THREAD

**Issue by FenixFyreX** [nilium/ruby-glfw3#4]
glfw3.c requires rb_num2uint, one of several functions created by ruby if and only if an int is smaller than a long. Check line 2072 of numeric.c:

``` c
#if SIZEOF_INT < SIZEOF_LONG
```

I recommend adding the same #if statement, with your code at line 535 within it. Add an #else statement and change all three calls to rb_num2uint, to rb_num2int. It compiled correctly then, with a warning on signed/unsigned integer conversion.

Edit: Also forgot to mention, I do believe that $LDFLAGS should be changed to $LIBS in extconf.rb, or you'll recieve all sorts of undefined references? At least I did...

**Comment by nilium** [comment]
Might be easier to just cast to `unsigned long` or (signed) `long` and not use the `int`-specific functions. Shouldn't result in truncation, at least. I'll look at it a little later. Thanks.

**Comment by FenixFyreX** [comment]
Yep :) Love this gem and thought I'd contribute.

**Comment by nilium** [comment]
As far as `$LDFLAGS` goes, using it is correct to the best of my knowledge. I'm not sure what `$LIBS` is used for or what the difference is, but use of LDFLAGS has so far worked fine since nobody's reported an issue with that. The only issues I've seen so far have been to do with people not compiling GLFW3 with the correct flags. Either way, it's used to pass the linker flags specified by glfw3.pc, so that's where they go.

I'd prefer a better way of handling the whole ld/cflags thing, but I haven't found one that's better than just using pkg-config yet.

**Comment by nilium** [comment]
And that should hopefully fix that, since NUM2UINT is defined regardless.
